### ISSUE TITLE
Why not use LiteLLM?

### ISSUE THREAD

**Issue by krrishdholakia** [haseeb-heaven/open-code-interpreter#1]
Hi @haseeb-heaven,

Curious what litellm was missing to be useful here? Any feedback would be great
https://github.com/haseeb-heaven/open-code-interpreter/blob/4c142036c430b1184c8eb420c8af804638ee73d1/interpreter.py#L7

**Comment by haseeb-heaven** [comment]
Thanks for suggestion, If you have reference for using LiteLLM with HugginFace models that would be great i would add definitely add that.

**Comment by haseeb-heaven** [comment]
Found some Resources and will add that in next update.

**Comment by haseeb-heaven** [comment]
Added Support with LiteLLM now :)
